AllCops:
  Exclude:
    - 'scripts/benchmark.rb'
    
Style/EndOfLine:
  Enabled: false

Metrics/MethodLength:
  Max: 25

Style/BlockComments:
  Enabled: false

Metrics/AbcSize:
  Max: 25

Style/RescueModifier:
  Enabled: false
